{{- if .Values.imagePullSecrets }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets }}
kind: Secret
metadata:
  name: registrysecrets
type: kubernetes.io/dockerconfigjson
{{- end -}}
